### ISSUE TITLE
Endpoints link is wrong

### ISSUE THREAD

**Issue by stacykor** [SumoLogic/livetail-cli#16]
![screen shot 2017-06-12 at 2 13 39 pm](https://user-images.githubusercontent.com/4722362/27059159-f240fe3e-4f89-11e7-9a89-364bd5813db5.png)

http://help.sumologic.com/Send_Data/Collector_Management_API/Sumo_Logic_Endpoints

**Comment by frankreno** [comment]
This is now fixed in 2.1
