### ISSUE TITLE
Consider moving configs into something not so generic

### ISSUE THREAD

**Issue by meeech** [SumoLogic/livetail-cli#20]
Consider using .livetail/config.json or some other variant. config.json is just too generic to be dropping into the root dir of someone's project.

**Comment by devmage** [comment]
A command-line option to pass a config.json path would also be great here.

**Comment by meeech** [comment]
no answer from sumologic.

**Comment by diversario** [comment]
Not only too generic but dropping config file into `cwd` is incredibly ridiculous, as it makes `livetail` config depend on where you invoke it, and re-entering credentials pretty much every time it runs gets really old real fast.
