### ISSUE TITLE
Documentation link is dead

### ISSUE THREAD

**Issue by delwaterman** [SumoLogic/livetail-cli#5]
The documentation link provided in the readme file is dead. https://service.sumologic.com/help/Default.htm#Live_Tail_CLI.htm

**Comment by riyasingh87** [comment]
HI @delwaterman Thanks for pointing it out! The doc links broke recently when we moved our Help to DocHub.

The corresponding help link is now at: http://help.sumologic.com/Search/Live_Tail/Live_Tail_CLI

Will fix in the CLI shortly.

**Comment by riyasingh87** [comment]
Fixed the readme file
