### ISSUE TITLE
optionally use env vars to read ID & Key & region

### ISSUE THREAD

**Issue by bosswissam** [SumoLogic/livetail-cli#8]
would be super useful so not to have to enter API secrets into bash history.

Entering region is useful because the way I use livetail is as follows:

`livetail "filter" | grep <subquery>
`
which would just hang if I ran this on a new shell and livetail doesn't remember my choice of region

**Comment by riyasingh87** [comment]
@bosswissam  - You don't have to enter the ID,Key,Regions if you don't want to. It needs to be entered once and is then stored in the config.json file in the same directory.

Try deleting the file and running the query again. It will ask you for the credentials only the first time. The next time onwards, you could directly run the query as above.
